### ISSUE TITLE
呼叫本地播放器無法獲取完整路徑, 主題問題, Markdown問題

### ISSUE THREAD

**Issue by foxdodo** [TW527E/renexmoe-tw527e-edition#1]
比如应该调用的是`potplayer://http://example.com/阿里云/视频/a.mp4`, 而实际使用时有几率出现只调用了路径 `potplayer://http://example.com/阿里云/视频/` 导致无法播放

![image](https://user-images.githubusercontent.com/3275698/165954369-a68319ed-7a67-4bbd-b11c-c0d93e9dc601.png)

控制台的错误日志, 不知道有没有帮助

**Comment by TW527E** [comment]
您好 (超官腔式回答)，您所發出的問題，已在 v1.0.8 版本解決 (應該啦w)，請您試著更新至 v1.0.8 或更新 (雖然目前沒有)，測試完成後，如依舊出現相同問題，請持續在此提出，此 issue 將在 14天後 關閉。

**Comment by TW527E** [comment]
（靠北 對不起 那個 commit 除了點問題ww 所以他瘋狂亂跳ww

**Comment by foxdodo** [comment]
调用播放器正常了🎉 感谢大佬
另外大佬平时都是用深色模式吗?  这个主题浅色模式下字体看的不太清楚, 而且样式会吧我MD文件的字体颜色都覆盖了
![image](https://user-images.githubusercontent.com/3275698/166091759-761852ea-3ee3-48bf-81e5-eadd1bb776f6.png)
如果不好改的话干脆强制默认深色模式也可以

**Comment by TW527E** [comment]
恩.. (實際上我是有弄背景所以淺色並沒有那麼辣眼睛)，那既然，你提出問題，我解決，那我改一改顏色w 然後處理一下 md 的問題

**Comment by foxdodo** [comment]
还有个问题, 手机移动端文件页面的下载按钮不见了🤣
换了几个手机浏览器1080p和2k分辨率都看不到右下角的下载按钮
![d4e81f0415b0a106e27cdcada7ac601](https://user-images.githubusercontent.com/3275698/166092675-38a506f7-f211-4c60-8ecc-8e9266dd4a20.jpg)

**Comment by TW527E** [comment]
右上角那個不是嗎?w

**Comment by TW527E** [comment]
哦不是ww 抱歉

**Comment by TW527E** [comment]
(介意加一下好友嗎? 這樣比較好交流w

**Comment by foxdodo** [comment]
加tg还是啥?

**Comment by TW527E** [comment]
tg

**Comment by foxdodo** [comment]
https://t.me/Wayne_47
