### ISSUE TITLE
请问更新到你的OneManager-php这个版本会解决登录，和预览文件的问题吗？

### ISSUE THREAD

**Issue by Adsryen** [TW527E/renexmoe-tw527e-edition#10]
1.登录 ，上次提到的  登录后  不跳转到后台界面
2.预览pdf，word，Excel，文件异常
![Snipaste_2022-07-08_11-53-34](https://user-images.githubusercontent.com/51238895/177913768-ccd868f9-e113-4a80-bcfd-6ca0f0843ade.png)

**Comment by TW527E** [comment]
Word, pdf Excel, PowerPoint 預覽正常 (至少我這正常
然後登入我測試也正常 如果密碼正確跳轉過後仍是遊客畫面 請F5或手動點擊刷新 以刷新至管理介面

![2022-07-08 17 26 41 replit-d tw527e eu org 96fe6c333ab0](https://user-images.githubusercontent.com/37478187/177962516-1559d6f1-967e-4b04-95e1-cf76283268cd.png)
![2022-07-08 17 21 57 replit-d tw527e eu org 817f60045c30](https://user-images.githubusercontent.com/37478187/177962552-359bc589-644f-441a-9c02-a2147b6ea353.png)
![2022-07-08 17 25 12 replit-d tw527e eu org 2ebdb0502861](https://user-images.githubusercontent.com/37478187/177962555-45c0a719-b4a0-4254-8658-cd389a6a2636.png)
![2022-07-08 17 25 28 replit-d tw527e eu org 8b54e169b1b1](https://user-images.githubusercontent.com/37478187/177962562-23ce6a76-4038-4f7c-a737-cece61527c72.png)

**Comment by TW527E** [comment]
(下面黑邊是因為我用瀏覽去的全畫面截圖 所以會造成此效果 抱歉qwq

**Comment by Adsryen** [comment]
哦哦哦  我更新到你的OneManager-php这个版本解决了，但是发现**阿里云的密码文件夹**却进不去了，onedrive的密码文件夹没有问题

**Comment by Adsryen** [comment]
另外我非常理解版权的问题，关于主题以及github页面的跳转完全没有意见，但还是希望能让用户，能有自定义添加页尾备案版权与备案号的权利，在内地备案的服务器部署，网安是强制要求页尾申明备案！侧栏的其余网站自定义超链接，例如博客也能自定义或许会更好，目前还在使用你上几次更新的模板文件

**Comment by Dedicatus5457** [comment]
直接改html往footer标签插入<a href="https://beian.miit.gov.cn/" target="_blank">xICP备xxxx号</a>即可

**Comment by Dedicatus5457** [comment]
直接改html往footer标签里插入`<a href="https://beian.miit.gov.cn/" target="_blank">xICP备XXXX号</a>`即可
或者在od里面新建一个文件foot.omf往文件里写这个html代码也行，om的foot.omf功能性文件支持html

**Comment by Adsryen** [comment]
> 

这是之前的模板文件可以改，但是最新这个就不行了  会直接跳转到github的界面，已经不允许修改了，我还在将就用着老版本的文件

**Comment by TW527E** [comment]
? 這個不行用嗎 ?
![image](https://user-images.githubusercontent.com/37478187/177985306-8ff18562-79b4-4ba9-860b-ce2d2d65692f.png)

**Comment by Adsryen** [comment]
眼瞎了 没看见   已解决

**Comment by TW527E** [comment]
@Adsryen 😂
