### ISSUE TITLE
游客登录网页白屏

### ISSUE THREAD

**Issue by mxtilx** [TW527E/renexmoe-tw527e-edition#12]
![Screenshot_2023-01-30-14-35-58-14](https://user-images.githubusercontent.com/96869052/215405534-b6e1858d-507f-4f75-bcec-cd99463ad6a1.jpg)
![Screenshot_2023-01-30-14-36-25-64](https://user-images.githubusercontent.com/96869052/215405539-06777937-a89b-4d2b-b35c-fcbc97e4fefb.jpg)

![Z7UEY{T6YFMMX8L0UK}RO@W(1)](https://user-images.githubusercontent.com/96869052/215405717-d64fca0c-b0f0-4cc0-bf06-4cbf113e512d.png)

**Comment by TW527E** [comment]
您好，如果是「遊客登入畫面」，不會有東西，因為這個主題把它閹割掉了。

**Comment by mxtilx** [comment]
> 你好，如果是「游客登录画面」，不会有东西，因为这个主题把它砍掉了。

那游客怎样看到文件，除了使用管理员

**Comment by TW527E** [comment]
1. 確認是否添加網盤
2. 確認網站緩存已清除 （因為有些平台有緩存
3. 將 customtheme 刪掉，我記得他會害當前主題出問題

恕我請問一下，您使用的平台是哪個，Vercel, Repl.it 還是什麼
因為我目前只有使用 Repl.it
如果是其他平台 我可能沒辦法幫助你

**Comment by mxtilx** [comment]
> 1. 确认是否添加网盘
> 2. 确认网站存档已清除（因为有一些平台有存档
> 3. 将customtheme剪掉，我记得他会害当时主题出题
> 
> 恕我请问一下，您使用的平台是哪个，Vercel, Repl.it 还是什么原因 因为我目前只有使用Repl.it 如果是其他平台我可能没办法帮助你

vercel

**Comment by TW527E** [comment]
然後我把當前主題打成了當時主題 抱歉

**Comment by TW527E** [comment]
誒 不對 是你的翻譯器翻錯 我還以為是我打錯

**Comment by mxtilx** [comment]
![U1XT ))PVBZKOIHTTQ`XX%5(1)](https://user-images.githubusercontent.com/96869052/215474950-5be24d85-ee48-4a51-8b4c-e1980a278cc7.png)
![LP19HZDL7R%U}5723}IPKOH(1)](https://user-images.githubusercontent.com/96869052/215474966-28ebf703-228f-40b8-b1ed-814605f9a465.png)

**Comment by mxtilx** [comment]
> 誒 不對 是你的翻譯器翻錯 我還以為是我打錯

这是什么问题

**Comment by TW527E** [comment]
這應該是你選的 cdn
可能是你連不上 或是他有問題
反正換一個 cdn 試試
（我指的是 你選的主題那喔 你現在選的是 statically 換一個試試
