### ISSUE TITLE
请问登录的问题有方法能解决吗

### ISSUE THREAD

**Issue by Adsryen** [TW527E/renexmoe-tw527e-edition#2]
非常感谢作者的开发，但是后台登录似乎很久都没有得到解决，应用主题后，onemanager作者说的  使用  ?admin 也会是无效，将无法登录后台，希望得到解决

**Comment by TW527E** [comment]
恩....
![image](https://user-images.githubusercontent.com/37478187/166480871-cf3a3903-cfec-4f9f-af35-bd799af33e97.jpeg)
顯然您使用的版本為新版本
那請使用 `?login=admin`

**Comment by TW527E** [comment]
抱歉，在您登入後，主題就自動且強制切換為 預設主題 了，因此無法為您多做協助，如您想提供此想法給預設主題的創作者，請向 [OneManager-php](https://github.com/qkqpttgf/OneManager-php) 提出 issue，感謝您的建議，雖然無法為您達成。

**Comment by TW527E** [comment]
**此 Issue 已關閉**，如尚有問題，請自行 `重新開始此 Issue` 或 `開啟新的 Issue`。
