### ISSUE TITLE
建议替换CDN

### ISSUE THREAD

**Issue by longda33** [TW527E/renexmoe-tw527e-edition#4]
建议将  cdn.jsdelivr.net   替换成  unpkg.com

**Comment by TW527E** [comment]
好的w 我試試w

**Comment by TW527E** [comment]
???

**Comment by TW527E** [comment]
您的要求已完成。
https://github.com/TW527E/renexmoe-tw527e-edition/releases/tag/v1.1.0

**Comment by longda33** [comment]
谢谢大佬！
