### ISSUE TITLE
请问侧边栏的目录是如何设置的？

### ISSUE THREAD

**Issue by syxf** [TW527E/renexmoe-tw527e-edition#5]
我在作者demo网站中看到侧边栏能显示一些目录，但是我找了一下设置好像又没有看到相关的选项，请教一下

**Comment by TW527E** [comment]
痾 其實就是直接多加幾個盤 然後那些盤的 public_path 設定要顯示的目錄就可以了

**Comment by TW527E** [comment]
![image](https://user-images.githubusercontent.com/37478187/168453389-70b63eb7-ef26-4ff6-8db5-5cd26cde8f59.png)
![image](https://user-images.githubusercontent.com/37478187/168453392-3aa7923e-c589-4859-aff7-2114954035b0.png)

**Comment by Dedicatus5457** [comment]
添加多个盘符自然就会在侧边栏显示，但是腾讯云函数最多只能添加四个，因为限制4kb。华为云函数则是只能添加两个，限制2kb。

**Comment by syxf** [comment]
原来是这样，感谢
